### ISSUE TITLE
grafana sourcing AWS credentials for cloudwatch datasource

### ISSUE THREAD

**Issue by m-richo** [vito/grafana-boshrelease#12]
firstly thanks for this bosh release.  got it deployed and hooked up to our graphite instance pretty easily!!  I then tried to setup AWS cloudwatch as a datasource in Grafana as per http://docs.grafana.org/datasources/cloudwatch/

Unfortunately grafana produced a `HTTP Error Internal Server Error` in the browser and the following in the logs

```
2016/08/29 11:01:05 [cloudwatch.go:139 handleListMetrics()] [E] Unable to call AWS API: NoCredentialProviders: no valid providers in chain
```

the Grafana docs imply it's looking for AWS credentials in $HOME/.aws/credentials which i had assumed to be /home/vcap/.aws/credentials but that didn't work at all.  

I'm not certain, but i believe the problem might be due to the `grafana_ctl` start/stop script launching the `grafana-server` process with the `chpst` command.  
`exec chpst -u vcap:vcap $PACKAGE_DIR/bin/grafana-server` results in the grafana-server process running as user `vcap`, but its environment variables including $HOME are for the user running the `grafana_ctl` script (root).  It therefore is trying to access /root/.aws/credentials for setting up a datastore.

Does this seem likely?  Or have you managed to get the cloudwatch datastore working?

Thanks,
Michael

**Comment by vito** [comment]
Either way is broken from a BOSH release perspective. There should be explicit properties added for configuring it so it can be set up in the manifest.

**Comment by m-richo** [comment]
Agreed that AWS cloudwatch credentials should be properties of the bosh job and be optionally set via deployment manifest.  I'm happy to send a PR, but thought i'd discuss first.

1 options could be to have `grafana_ctl`  create `/home/vcap/.aws/credentials` if AWS credentials were provided in deployment manifest, and that the `chpst` command could be replaced with `su -c` in order for the `grafana-server` process to use the `vcap` users environment variables.

Can you think of a neater way of doing it?

**Comment by vito** [comment]
Bleh, that's pretty annoying that you can only configure it with either global state on your OS user or global state on the entire machine. :( I really don't like the idea of a BOSH release modifying the user's home directory. Maybe it could create some other dir and export it as `$HOME` when running the grafana process?

**Comment by m-richo** [comment]
Let me run some tests with setting $HOME to some arbitrary directory under /var/vcap/<somewhere> that contains the .aws/credentials file and see if that even works.

I think you can specify additional or overriding environment variables to `chpst` with the `-e` switch.  

Let me get back to you.
