### ISSUE TITLE
Need a license to contribute

### ISSUE THREAD

**Issue by holgero** [vito/grafana-boshrelease#2]
Hi @vito,

we would like to use your bosh-release and to contribute. But as a prerequisite we first need a license. We created a pull request with a apache license 2.0 (#1) for your convenience (other licenses might be
OK for us too, but apache one of the easiest for us to consume and it is also used in other cloudfoundry projects).

A question: Could this project be moved to one of the cloudfoundry organisations? (perhaps cloudfoundry-community?) That would make it easier for us to pass our own corporate legal requirements.

Best regards,
Holger.

**Comment by vito** [comment]
This won't be moving to the cloudfoundry organizations, but I'll gladly accept the license PR - forgot about that. Thanks!
