### ISSUE TITLE
Upgrade Concourse to Later Version?

### ISSUE THREAD

**Issue by keithkroeger** [vito/grafana-boshrelease#30]
Hi @vito, any thoughts about upgrading this older grafana to a later 5.2*?

Thank you

**Comment by toddboom** [comment]
@keithkroeger We're working on getting this bumped to 6.1.0, which was just released. Stay tuned.

**Comment by toddboom** [comment]
@keithkroeger This is now bumped to Grafana 6.1.1. Please let us know if you see any config options that are missing, as we haven't had time to do a full sweep yet.
