### ISSUE TITLE
Grafana-2.6

### ISSUE THREAD

**Issue by holgero** [vito/grafana-boshrelease#4]
Hi Alex,

I am currently preparing a new boshrelease with grafana-2.6 (I'll create a pull request within the next week) and I am wondering which of the new options to pass through as properties to fill in.
I started with the grafana-2.6/conf/samples.ini file from the tar ball and inserted all the current configurable options we have in config.ini.erb.
The new options I would like to make configurable also are the ones in the [auth.proxy] section.

Anything else I should add immediately? Or would you prefer to discuss this when I have the pull request ready?

Best Regards,
Holger.

**Comment by vito** [comment]
merged the PR, thanks! sorry, didn't get notifications for any of this
